### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by tomer1** [deneb42/SublimeLogReader#3]
did all the steps  as descripe but still not coloring

**Comment by deneb42** [comment]
Hello,
I have two questions in order to get a better understanding of what happens : 
- Have you installed the plugin manually, or with packageControl ?
- Is the theme changing when you use Android or iOS log coloration ? (the background should be a bit darker than Molokaï's normal background)  
  Furthermore, if you can tell me what OS and SublimeText version you're using, it might help as well.
  Thanks

**Comment by tomer1** [comment]
i had install with the packageControl.
Yes, the theme change to be a bit darker 

Am running ubuntu 14.10 64-bit 
and sublime Build 3065

**Comment by deneb42** [comment]
Ok,
Can you share a bit of logs (if there is no critical information in it).
You might have a logs format that I haven't encountered yet (and thus isn't supported)

**Comment by tomer1** [comment]
I also try to install the plugin manually now, still same result 
in additonal I upgrade sublime now to version 3080 

DPI scale: 1
startup, version: 3080 linux x64 channel: stable
executable: /opt/sublime_text/sublime_text
working dir: /
packages path: /home/tomer/.config/sublime-text-3/Packages
state path: /home/tomer/.config/sublime-text-3/Local
zip path: /opt/sublime_text/Packages
zip path: /home/tomer/.config/sublime-text-3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.079015
startup time: 0.163568
first paint time: 0.165801
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.quick_panel
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-ssl-linux
Linux SSL: successfully loaded _ssl module for libssl.so.1.0.0
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Package Control.Package Control
reloading plugin Package Control.bootstrap
reloading plugin MobileLogReader.logFilter
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2015-03-24 16:14:58, next run at 2015-03-24 17:14:58 or after

**Comment by deneb42** [comment]
Are those the logs you're trying to colorize ?

**Comment by tomer1** [comment]
no those are the log from sublime console 

my log:
03-22 20:47:44.423  1058 20477 D SIP UA Receiver: > UNLOCK CPU 0
03-22 20:47:44.423  1058  3043 D PjService: Profile updated for 0
03-22 20:47:44.423  1058  3043 D PjService: Profile updated for 0 with status code= 200
03-22 20:47:44.423  1058  3043 V KPjSipService: isAccountRegistered - start
03-22 20:47:44.423  1058  3043 V KPjSipService: Account is registered
03-22 20:47:44.423  1058  3043 V SipWakeLock: release wakelock: holder count=0 []
03-22 20:47:44.433  1058  1058 V Timer wrap: FIRE Received TIMER 908 14218821 vs 14218822

**Comment by deneb42** [comment]
Ok, I think that I see where the problem comes from.
Your formatting differ from those i've seen until now : 
Until now, I've seen things like 
03-22 20:47:44.423 1058 3043 V/ProgName(pid): Message
I'll change the regexp to have the couple ProgName(pid) optionnal.
for my curiosity, what utility are you using to get your logs ? logcat ? with special parameters ?

**Comment by tomer1** [comment]
I take log from the device with adb logcat -vthreadtime 
http://developer.android.com/tools/debugging/debugging-log.html#outputFormat

**Comment by tomer1** [comment]
@deneb42  

any news  ?

**Comment by deneb42** [comment]
Hello, 
Sorry for the delay, but due to a certain number of things I couldn't work on the plugin for the last few weeks.
I'll take add support for all logcat output asap (thanks for the doc btw)

**Comment by deneb42** [comment]
Hello, 
I completely refactored the regex for Android log.
The plugin now support all the logcat formats, threadtime included.
I'm closing the issue, but feel free to reopen it if you still got problems.
Thanks for reporting, and once again sorry for the delay.

**Comment by tomer1** [comment]
Great, it's works flowless,

thanks alot !!
